# Generated by Django 4.1.5 on 2023-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionfrequency',
            options={'verbose_name_plural': 'Collection Frequencies'},
        ),
        migrations.RemoveField(
            model_name='collectionfrequency',
            name='entries',
        ),
        migrations.AddField(
            model_name='collectionfrequency',
            name='num_entries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
