# Generated by Django 4.1.5 on 2023-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdo',
            name='pdo_num',
            field=models.IntegerField(),
        ),
    ]
