# Generated by Django 4.1.5 on 2023-02-07 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_rename_is_manager_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_month', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prefix', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubPDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpdo_id', models.IntegerField(editable=False, unique=True)),
                ('result_level', models.CharField(choices=[], default='', max_length=20)),
                ('indicator', models.CharField(choices=[], default='', max_length=20)),
                ('classification', models.CharField(choices=[], default='', max_length=20)),
                ('measurement_unit', models.CharField(choices=[], default='', max_length=20)),
                ('baseline', models.IntegerField(default=1)),
                ('baseline_year_field', models.DateField(auto_now_add=True)),
                ('actual_to_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perc_complete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detailed_data_src', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='reporters',
            field=models.ManyToManyField(related_name='editing_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_id', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('str_start_date', models.CharField(max_length=150)),
                ('actual_to_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perc_complete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.TimeField(auto_now_add=True)),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_year', to='baseApp.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Pdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pdo_id', models.IntegerField(unique=True)),
                ('subpdos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdo', to='baseApp.subpdo')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='collection_freq',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.collectionfrequency'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='baseApp.pdo'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_years',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.projectyear'),
        ),
    ]
