# Generated by Django 4.1.5 on 2023-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_rename_year_id_projectyear_year_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectyear',
            name='perc_complete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
