# Generated by Django 4.1.5 on 2023-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_collectionfrequency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectyear',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
