# Generated by Django 4.1.5 on 2023-02-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_collection_collectionfrequency_subpdo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpdo',
            name='subpdo_id',
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='actual_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='classification',
            field=models.CharField(choices=[('1', 1), ('2', 2)], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='detailed_data_src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='end_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='indicator',
            field=models.CharField(choices=[('1', 1), ('2', 2)], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='measurement_unit',
            field=models.CharField(choices=[('1', 1), ('2', 2)], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='perc_complete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='result_level',
            field=models.CharField(choices=[('1', 1), ('2', 2)], default='', max_length=20),
        ),
    ]
