# Generated by Django 4.1.5 on 2023-02-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_projectyear_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectyear',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
