# Generated by Django 4.1.5 on 2023-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_alter_pdo_options_remove_pdo_unique_pdo_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdo',
            options={'ordering': ['project'], 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AddConstraint(
            model_name='pdo',
            constraint=models.UniqueConstraint(fields=('project', 'pdo_num'), name='unique_pdo_num'),
        ),
    ]
