# Generated by Django 4.1.5 on 2023-02-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_alter_projectyear_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectyear',
            name='unique_id',
        ),
    ]
