# Generated by Django 4.1.5 on 2023-02-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_remove_subpdo_subpdo_id_alter_subpdo_actual_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_years',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.projectyear'),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='actual_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='perc_complete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='str_start_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projectyear',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
