# Generated by Django 4.1.5 on 2023-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_pdo_options_pdo_unique_pdo_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='classification',
            field=models.CharField(choices=[('Cummulative', 'Cummulative'), ('Number', 'Number'), ('Percentage', 'Percentage')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='measurement_unit',
            field=models.CharField(choices=[('Number', 'Number'), ('Percentage', 'Percentage')], default='', max_length=20),
        ),
    ]
