# Generated by Django 4.1.5 on 2023-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_projectyear_year_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectyear',
            name='year_entries',
            field=models.ManyToManyField(blank=True, related_name='project_year', to='baseApp.yearentries'),
        ),
    ]
