# Generated by Django 4.1.5 on 2023-02-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_remove_projectyear_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectyear',
            name='collection_freq',
        ),
        migrations.AddField(
            model_name='projectyear',
            name='collection_freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_year', to='baseApp.collectionfrequency'),
        ),
    ]
