# Generated by Django 4.1.5 on 2023-02-07 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_remove_project_creator_customuser_created_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genPDO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporters',
            field=models.ManyToManyField(blank=True, related_name='editing_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
