# Generated by Django 4.1.5 on 2023-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_entry_index_alter_entry_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='index',
            field=models.IntegerField(),
        ),
    ]
