# Generated by Django 4.1.5 on 2023-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_entry_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
