# Generated by Django 4.1.5 on 2023-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_project_reporters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectyear',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_years',
            field=models.ManyToManyField(blank=True, related_name='projects', to='baseApp.projectyear'),
        ),
    ]
