# Generated by Django 4.1.5 on 2023-02-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_entry_options_alter_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpdo',
            name='actual_to_date',
        ),
        migrations.RemoveField(
            model_name='subpdo',
            name='perc_complete',
        ),
        migrations.AlterField(
            model_name='subpdo',
            name='end_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='YearlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yrly_target_index', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('subpdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='baseApp.subpdo')),
            ],
        ),
    ]
