# Generated by Django 4.1.5 on 2023-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_remove_subpdo_actual_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlytarget',
            name='value',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
