# Generated by Django 4.1.5 on 2023-02-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_alter_yearlytarget_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlytarget',
            name='value',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
