# Generated by Django 4.1.5 on 2023-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_alter_entry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
    ]
