# Generated by Django 4.1.5 on 2023-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_alter_entry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpdo',
            name='end_target',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
