# Generated by Django 4.1.5 on 2023-03-24 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0018_rename_only_view_project_only_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='only_viewers',
            field=models.ManyToManyField(blank=True, related_name='view_only_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
