# Generated by Django 4.1.5 on 2023-03-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_alter_projectyear_collection_freq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdo',
            options={'ordering': ['project'], 'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AlterModelOptions(
            name='subpdo',
            options={'ordering': ['pdo'], 'verbose_name': 'Project Development objective', 'verbose_name_plural': 'Project Development objectives'},
        ),
        migrations.RenameField(
            model_name='yearlytarget',
            old_name='yrly_target_index',
            new_name='year',
        ),
    ]
