# Generated by Django 4.1.3 on 2023-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_alter_pdo_options_alter_subpdo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlytarget',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
